#Decision Tree with tree visualization

You have to install dtreeviz

In [1]:
!pip install -q dtreeviz

Import the dtreeviz, IPython's imahe display and pandas


In [2]:
from dtreeviz.trees import *
from IPython.display import Image, display_svg, SVG
import pandas as pd

Import the dataset from Github


In [3]:
url = "https://github.com/IndraniMandal/CSC310-S20/blob/master/notes/assets/iris.csv"

In [4]:
url = "https://raw.githubusercontent.com/IndraniMandal/CSC310-S20/master/notes/assets/iris.csv"

In [5]:
df = pd.read_csv(url)
df

id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
..   ...           ...          ...           ...          ...        ...
145  146           6.7          3.0           5.2          2.3  virginica
146  147           6.3          2.5           5.0          1.9  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[150 rows x 6 columns]

Seperate the target column 'Species' from the rest of the dataset. Create the training features(X_train) and the target(y_train)

In [6]:
features_df = df.drop(['id','Species'],axis=1)# features
features_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [7]:
target_df = pd.DataFrame(df['Species']) # y_Train
target_df.head()

Species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa

dtreeviz accepts targets as numpy array only so let's convert the target 'Species' into an 1 dimentional numpy array by 
1. replace the categories("setosa"--> 1) into numerical values. 
2. convert the target_df dataframe to numpy array. 
3. flatten the 2D array into 1D array

In [8]:
target_df['Species'].replace(["setosa", "versicolor", "virginica"], [1,2,3], inplace=True)

In [9]:
import numpy as np
target_df= target_df.to_numpy()
target_df= target_df.flatten()
target_df

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

Build the model (dtree)
Fit the model with your training features(features_df) and target(target_df)

In [10]:
dtree = tree.DecisionTreeClassifier(criterion='entropy')
dtree.fit(features_df,target_df)

DecisionTreeClassifier(criterion='entropy')

In [11]:
features_df.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width'], dtype='object')

Time to visualize the decision tree, features_df is a dataframe, target_df is a, 1D numpy array

In [12]:
viz = dtreeviz(dtree, # The model we have just created
               features_df, # Training featues(dataframe)
               target_df,  # Target(1D numpy array)
               target_name='Species',
               feature_names= features_df.columns, # Name of the features
               class_names= ["setosa", "versicolor", "virginica"] # need class_names for classifier
              )  

In [13]:
viz

ExecutableNotFound: failed to execute 'dot', make sure the Graphviz executables are on your systems' PATH

Check for accuracy, let's just test it against our training data(features_df) and see how it does with data it has already seen. In the next session we will test it with data the model had not seen before. Test for accuracy by comparing the predicted labels against the true target values(target_df)

In [14]:
from sklearn.metrics import accuracy_score
predicted_labels = dtree.predict(features_df)  #predicts a label for the features 

#Test for accuracy
print("Our model accuracy is: {}".format(accuracy_score(target_df, predicted_labels
                                                        )))

Our model accuracy is: 1.0


Of course accuracy is 100% because it's been tested on data it has already seen. Notice the predicted labels values and exactly same as the target values(y_train)

In [15]:
predicted_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [16]:
target_df

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

Let's try to build a tree that's not fully grown, it only grows upto a depth of 2

In [17]:
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=2)
dtree.fit(features_df,target_df)

DecisionTreeClassifier(criterion='entropy', max_depth=2)

In [18]:
viz = dtreeviz(dtree, # The model we have just created
               features_df, # Training featues(dataframe)
               target_df,  # Target(1D numpy array)
               target_name='Species',
               feature_names=features_df.columns, # Name of the features
               class_names= ["setosa", "versicolor", "virginica"] # need class_names for classifier
              )  
viz

ExecutableNotFound: failed to execute 'dot', make sure the Graphviz executables are on your systems' PATH

In [19]:
predicted_labels = dtree.predict(features_df)  #predicts a label for the features 

#Test for accuracy
print("Our model accuracy is: {}".format(accuracy_score(target_df, predicted_labels
                                                        )))

Our model accuracy is: 0.96


Notice when we don't grow the full tree, the accuracy of the predicted label values only drop by 4%. Not too bad!